let allTracks=[];let activeCat='Tout';let query='';

function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)}
async function copyCommand(id){const cmd='!song #'+id;try{await navigator.clipboard.writeText(cmd);toast('Commande copiée : '+cmd)}catch(e){const ta=document.createElement('textarea');ta.value=cmd;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();toast('Commande copiée : '+cmd)}}
function categories(){return [...new Set(allTracks.map(t=>t.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr'))}
function renderFilters(){const f=document.getElementById('filters');const cats=['Tout',...categories()];f.innerHTML=cats.map(c=>`<button class="chip ${c===activeCat?'active':''}" data-cat="${encodeURIComponent(c)}">${esc(c)}</button>`).join('');f.querySelectorAll('.chip').forEach(b=>b.addEventListener('click',()=>{activeCat=decodeURIComponent(b.dataset.cat);renderFilters();render()}))}
function filtered(){const q=query.trim().toLocaleLowerCase('fr');return allTracks.filter(t=>{const cat=activeCat==='Tout'||t.category===activeCat;const txt=(t.title+' '+t.artist+' '+t.category+' '+t.id).toLocaleLowerCase('fr');return cat&&(!q||txt.includes(q))})}
function render(){const tracks=filtered();document.getElementById('count').textContent=`${tracks.length} morceau${tracks.length>1?'x':''} affiché${tracks.length>1?'s':''} sur ${allTracks.length}`;document.getElementById('modehint').textContent=activeCat==='Tout'?'Tous les genres':activeCat;const g=document.getElementById('grid');if(!tracks.length){g.innerHTML='<div class="empty">Aucun morceau ne correspond à cette recherche.</div>';return}g.innerHTML=tracks.map(t=>`<article class="card"><div class="topline"><span class="id">#${t.id}</span><span class="tag">${esc(t.category||'Général')}</span></div><div class="title">${esc(t.title)}</div><div class="artist">${esc(t.artist)}</div><div class="spacer"></div><button class="request" data-id="${t.id}">Demander ce morceau</button></article>`).join('');g.querySelectorAll('.request').forEach(b=>b.addEventListener('click',()=>copyCommand(b.dataset.id)))}
function randomTrack(){const a=filtered();if(!a.length){toast('Aucun morceau dans cette sélection.');return}const t=a[Math.floor(Math.random()*a.length)];document.getElementById('search').value=t.title;query=t.title;render();window.scrollTo({top:document.querySelector('.summary').offsetTop-90,behavior:'smooth'})}
async function load(){try{const r=await fetch('catalog.json',{cache:'no-store'});if(!r.ok)throw new Error('catalogue');allTracks=await r.json()}catch(e){document.getElementById('grid').innerHTML='<div class="empty">Le catalogue musical n’est pas encore publié. Revenez bientôt.</div>';document.getElementById('count').textContent='Catalogue indisponible';return}renderFilters();render()}
document.getElementById('search').addEventListener('input',e=>{query=e.target.value;render()});document.getElementById('randomBtn').addEventListener('click',randomTrack);load();
