let allTracks=[];
let view={level:'categories',category:null,album:null};
let query='';
let liveEndpoint='';

const PALETTE=[['#0B4C55','#0E6872'],['#2F673A','#4D8757'],['#77542E','#A17843'],['#5B456F','#80639A'],['#7A3948','#A65368'],['#315B77','#4E7D9E'],['#655E2E','#8F8643'],['#6E4535','#96614B']];

function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function hash(s){let h=0;for(const c of String(s)){h=((h<<5)-h)+c.charCodeAt(0);h|=0}return Math.abs(h)}
function colors(name){return PALETTE[hash(name)%PALETTE.length]}
function initials(s){return String(s||'?').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2400)}
async function copyCommand(id){const cmd='!song #'+id;try{await navigator.clipboard.writeText(cmd);toast('Commande copiée : '+cmd)}catch(e){const ta=document.createElement('textarea');ta.value=cmd;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();toast('Commande copiée : '+cmd)}}

function groupCategories(){const m=new Map();for(const t of allTracks){const c=t.category||'Autres';if(!m.has(c))m.set(c,{name:c,tracks:0,albums:new Set()});const x=m.get(c);x.tracks++;x.albums.add(t.album||'Sans album')}return [...m.values()].sort((a,b)=>a.name.localeCompare(b.name,'fr'))}
function groupAlbums(category){const m=new Map();for(const t of allTracks.filter(t=>(t.category||'Autres')===category)){const a=t.album||'Sans album';if(!m.has(a))m.set(a,{name:a,category,tracks:0,artist:t.artist||'StreamBeats',cover:t.cover||''});const x=m.get(a);x.tracks++;if(!x.cover&&t.cover)x.cover=t.cover}return [...m.values()].sort((a,b)=>a.name.localeCompare(b.name,'fr'))}
function tracksFor(category,album){return allTracks.filter(t=>(t.category||'Autres')===category&&(t.album||'Sans album')===album).sort((a,b)=>a.title.localeCompare(b.title,'fr',{numeric:true}))}

function setView(level,category=null,album=null){view={level,category,album};query='';document.getElementById('search').value='';render();window.scrollTo({top:document.querySelector('.breadcrumb').offsetTop-12,behavior:'smooth'})}
function renderBreadcrumb(){const b=document.getElementById('breadcrumb');let h=`<button class="crumb ${view.level==='categories'?'active':''}" data-level="categories">Styles</button>`;if(view.category)h+=`<span>›</span><button class="crumb ${view.level==='albums'?'active':''}" data-level="albums">${esc(view.category)}</button>`;if(view.album)h+=`<span>›</span><span class="crumb active">${esc(view.album)}</span>`;b.innerHTML=h;b.querySelector('[data-level="categories"]')?.addEventListener('click',()=>setView('categories'));b.querySelector('[data-level="albums"]')?.addEventListener('click',()=>setView('albums',view.category))}
function searchTracks(q){const n=q.trim().toLocaleLowerCase('fr');if(!n)return[];return allTracks.filter(t=>[t.title,t.artist,t.category,t.album,t.id].join(' ').toLocaleLowerCase('fr').includes(n))}

function coverHTML(item,kind){const name=item.name;const[a,b]=colors(kind==='category'?name:(item.category||name));if(kind==='album'&&item.cover)return `<div class="cover album-cover" style="--ca:${a};--cb:${b}"><img src="${esc(item.cover)}" alt="" loading="lazy" onerror="this.remove();this.parentElement.classList.add('fallback')"><span>${esc(initials(name))}</span></div>`;return `<div class="cover ${kind}-cover fallback" style="--ca:${a};--cb:${b}"><span>${esc(initials(name))}</span></div>`}

function renderSearch(){const tracks=searchTracks(query);document.getElementById('count').textContent=`${tracks.length} résultat${tracks.length>1?'s':''}`;document.getElementById('modehint').textContent='Recherche globale';const g=document.getElementById('grid');if(!tracks.length){g.innerHTML='<div class="empty">Aucun résultat dans le catalogue.</div>';return}g.innerHTML=tracks.map(trackCard).join('');bindTrackButtons()}
function renderCategories(){const cats=groupCategories();document.getElementById('count').textContent=`${cats.length} style${cats.length>1?'s':''}`;document.getElementById('modehint').textContent=`${allTracks.length} morceaux`;const g=document.getElementById('grid');g.innerHTML=cats.map(c=>{const[a,b]=colors(c.name);return `<article class="browse-card category-card" data-category="${encodeURIComponent(c.name)}" style="--ca:${a};--cb:${b}">${coverHTML(c,'category')}<div class="browse-body"><span class="kicker">Style</span><h2>${esc(c.name)}</h2><p>${c.albums.size} album${c.albums.size>1?'s':''} · ${c.tracks} morceau${c.tracks>1?'x':''}</p><button class="open-btn">Explorer ce style <span>→</span></button></div></article>`}).join('');g.querySelectorAll('.category-card').forEach(card=>card.addEventListener('click',()=>setView('albums',decodeURIComponent(card.dataset.category))))}
function renderAlbums(){const albums=groupAlbums(view.category);document.getElementById('count').textContent=`${albums.length} album${albums.length>1?'s':''}`;document.getElementById('modehint').textContent=view.category;const g=document.getElementById('grid');g.innerHTML=albums.map(a=>`<article class="browse-card album-card" data-album="${encodeURIComponent(a.name)}">${coverHTML(a,'album')}<div class="browse-body"><span class="kicker">${esc(view.category)}</span><h2>${esc(a.name)}</h2><p>${a.tracks} morceau${a.tracks>1?'x':''}</p><button class="open-btn">Voir l'album <span>→</span></button></div></article>`).join('');g.querySelectorAll('.album-card').forEach(card=>card.addEventListener('click',()=>setView('tracks',view.category,decodeURIComponent(card.dataset.album))))}
function trackCard(t){const[a,b]=colors(t.category||'Autres');return `<article class="track-card"><div class="track-cover" style="--ca:${a};--cb:${b}">${t.cover?`<img src="${esc(t.cover)}" alt="" loading="lazy" onerror="this.remove()">`:''}<span>♫</span></div><div class="track-main"><div class="track-meta"><span class="id">#${t.id}</span><span class="tag">${esc(t.category||'Autres')}</span></div><div class="title">${esc(t.title)}</div><div class="artist">${esc(t.artist)}</div></div><button class="request" data-id="${t.id}">Demander</button></article>`}
function bindTrackButtons(){document.querySelectorAll('.request').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();copyCommand(b.dataset.id)}))}
function renderTracks(){const tracks=tracksFor(view.category,view.album);document.getElementById('count').textContent=`${tracks.length} morceau${tracks.length>1?'x':''}`;document.getElementById('modehint').textContent=view.album;const g=document.getElementById('grid');if(!tracks.length){g.innerHTML='<div class="empty">Cet album est vide.</div>';return}g.innerHTML=tracks.map(trackCard).join('');bindTrackButtons()}
function render(){renderBreadcrumb();if(query.trim())return renderSearch();if(view.level==='categories')return renderCategories();if(view.level==='albums')return renderAlbums();return renderTracks()}

function surprise(){let pool=allTracks;if(view.level==='albums'&&view.category)pool=allTracks.filter(t=>(t.category||'Autres')===view.category);if(view.level==='tracks'&&view.album)pool=tracksFor(view.category,view.album);if(!pool.length)return toast('Aucun morceau disponible.');const t=pool[Math.floor(Math.random()*pool.length)];setView('tracks',t.category||'Autres',t.album||'Sans album');setTimeout(()=>{const btn=document.querySelector(`.request[data-id="${t.id}"]`);btn?.scrollIntoView({behavior:'smooth',block:'center'});btn?.closest('.track-card')?.classList.add('highlight');setTimeout(()=>btn?.closest('.track-card')?.classList.remove('highlight'),2200)},150)}

async function loadLiveConfig(){try{const r=await fetch('live-config.json',{cache:'no-store'});if(!r.ok)return;const c=await r.json();liveEndpoint=(c.endpoint||'').replace(/\/$/,'');if(liveEndpoint){document.getElementById('livePanel').hidden=false;await refreshLive();setInterval(refreshLive,3000)}}catch(e){}}
async function refreshLive(){if(!liveEndpoint)return;try{const r=await fetch(liveEndpoint+'/live',{cache:'no-store'});if(!r.ok)throw new Error('live');const s=await r.json();const cur=document.getElementById('liveCurrent');cur.innerHTML=s.current?`<div><span class="kicker">En cours</span><strong>${esc(s.current.title)}</strong><span>${esc(s.current.artist)} · ${esc(s.current.album||'')}</span></div>`:`<div><span class="muted">Aucun morceau en cours.</span></div>`;document.getElementById('queueCount').textContent=s.queue_length||0;const q=document.getElementById('liveQueue');q.innerHTML=(s.queue||[]).length?s.queue.map(x=>`<div class="queue-row"><span class="queue-pos">${x.position}</span><div><strong>${esc(x.title)}</strong><span>${esc(x.requested_by?('Demandé par '+x.requested_by):x.album)}</span></div></div>`).join(''):`<div class="queue-empty">La file est vide : la lecture continue automatiquement dans le même album, puis le même style.</div>`;document.getElementById('liveUpdated').textContent='mis à jour'}catch(e){document.getElementById('liveUpdated').textContent='hors ligne'}}

async function load(){try{const r=await fetch('catalog.json',{cache:'no-store'});if(!r.ok)throw new Error('catalog');allTracks=await r.json();allTracks=allTracks.map(t=>({...t,category:t.category||'Autres',album:t.album||t.category||'Sans album',cover:t.cover||''}))}catch(e){document.getElementById('grid').innerHTML='<div class="empty">Le catalogue musical n’est pas encore publié.</div>';document.getElementById('count').textContent='Catalogue indisponible';return}render();loadLiveConfig()}

document.getElementById('search').addEventListener('input',e=>{query=e.target.value;render()});
document.getElementById('randomBtn').addEventListener('click',surprise);
load();
